### ISSUE TITLE
Needs updating for latest build of EF..

### ISSUE THREAD

**Issue by dazinator** [natemcmaster/entityframework-provider-starter#2]
Using the latest build of EF, the base class `Database` no longer seems to have a constructor that accepts just 1 argument.

Therefore the example `ProviderDatabase` class, doesn't want to compile against the latest NuGet release of EF.

**Comment by natemcmaster** [comment]
Yeah, this repo is extremely out of date. EF 7 has continued to evolve and I haven't kept this up to date. Once the core APIs settle for EF 7, I'll revisit this repo and update it. Sorry about that!

**Comment by dazinator** [comment]
No worries - makes perfect sense, I can wait :)

**Comment by natemcmaster** [comment]
Actually, I posted an update earlier. It didn't take too much to get it working with the latest build. The APIs may still change in the future, though.

**Comment by dazinator** [comment]
Great - understood, thanks.
