### ISSUE TITLE
When will this be updated?

### ISSUE THREAD

**Issue by neil-119** [natemcmaster/entityframework-provider-starter#3]
On the "Writing an EF7 Provider" page, it mentions that the article is out of date. I'm just curious as to when this will be updated (I understand that there are many other things that are priority). I was working on a LINQ provider when I ran across this and thought might be better.

**Comment by natemcmaster** [comment]
Excellent question. We are hard at work writing docs for our upcoming release of EF 7. You can see the progress at https://github.com/aspnet/EntityFramework.Docs, available in more-readable format at http://ef.readthedocs.org.

For providers, we will be writing more extensive documentation in http://ef.readthedocs.org/en/latest/providers/index.html. As EF 7 is still a WIP, some of the EF.Core APIs are subject to change.

**Comment by natemcmaster** [comment]
Updated for RC2
